/**
 * Greenfield Partners — Portfolio Company Data
 * Single source of truth for all portfolio companies.
 * Assets live in:
 *   Favicons    → assets/Favicons/<name>
 *   BG images   → assets/portfolio bgs/<name>
 *   Color logos  → assets/portfolio logo colors/<name>
 */

const PORTFOLIO = [

    // ── Currently on Dashboard ─────────────────────────────────────────────

    {
        id: 'vast',
        name: 'VAST Data',
        sector: 'AI Infrastructure',
        category: 'ai-infra',
        description: 'The Data Platform Company for the AI Era',
        round: 'Led Series B',
        year: 2019,
        featured: true,                 // spans 2-col in bento grid
        status: 'active',
        ceo: 'Renen Hallak',
        website: 'http://vastdata.com/',
        favicon: 'assets/Favicons/vast favicon.png',
        bg: 'assets/portfolio bgs/vast bg.png',
        logo: 'assets/portfolio logo colors/VAST Data logo color.svg',
    },
    {
        id: 'coralogix',
        name: 'Coralogix',
        sector: 'IT Infrastructure',
        category: 'it-infra',
        description: 'Observability and Security that Scale with You',
        round: 'Led Series C',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Ariel Assaraf',
        website: 'https://www.coralogix.com/',
        favicon: 'assets/Coralogix/cropped-cropped-favicon-192x192.png',
        bg: 'assets/portfolio bgs/coralogix bg.png',
        logo: 'assets/portfolio logo colors/Coralogix Logo Use.png',
    },
    {
        id: 'exodigo',
        name: 'Exodigo',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'Non-Intrusive Subsurface Imaging',
        round: 'Led Series A',
        year: 2023,
        featured: false,
        status: 'active',
        ceo: 'Jeremy Suard',
        website: 'http://exodigo.com/',
        favicon: 'assets/Favicons/exodigo favicon.png',
        bg: 'assets/portfolio bgs/exodigo bg.png',
        logo: 'assets/portfolio logo colors/Exodigo logo color.svg',
    },
    {
        id: 'robco',
        name: 'RobCo',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'The Robot Company centered on Software and AI',
        round: 'Series C',
        year: 2026,
        featured: false,
        status: 'active',
        ceo: 'Roman Hölzl',
        website: 'https://www.rob.co/',
        favicon: 'assets/Favicons/robco favicon.png',
        bg: 'assets/portfolio bgs/robco bg.png',
        logo: 'assets/portfolio logo colors/RobCo logo color.png',
    },
    {
        id: 'torq',
        name: 'Torq',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'AI-Native Hyperautomation for Security Teams',
        round: 'Led Series B',
        year: 2023,
        featured: false,
        status: 'active',
        ceo: 'Ofer Smadari',
        website: 'https://torq.io/',
        favicon: 'assets/Favicons/torq favicon.png',
        bg: 'assets/portfolio bgs/torq bg.png',
        logo: 'assets/portfolio logo colors/Torq logo color.avif',
    },
    {
        id: 'aai',
        name: 'AAI',
        sector: 'AI Infrastructure',
        category: 'aai',
        description: 'Cracking the Code<br>of Superintelligence',
        round: 'Series A',
        year: 2025,
        featured: false,
        status: 'active',
        ceo: 'Prof. Amnon Shashua',
        website: 'https://doubleai.com/',
        favicon: 'assets/Favicons/AAI favicon.png',
        bg: 'assets/portfolio bgs/aai bg.png',
        logo: 'assets/portfolio logo colors/AAI Logo.png',
    },
    {
        id: 'silverfort',
        name: 'Silverfort',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'Where Identity Security has Never Gone Before',
        round: 'Led Series C',
        year: 2022,
        featured: false,
        status: 'active',
        ceo: 'Hed Kovetz',
        website: 'http://silverfort.com/',
        favicon: 'assets/Favicons/silverfort favicon.png',
        bg: 'assets/portfolio bgs/silverfort bg.png',
        logo: 'assets/portfolio logo colors/Silverfort Logo Use.png',
    },

    // ── Staged — ready to pull into dashboard ─────────────────────────────

    {
        id: 'bigpanda',
        name: 'BigPanda',
        sector: 'IT Infrastructure',
        category: 'it-infra',
        description: 'Event Correlation & Automation Platform',
        round: 'Led Series B',
        year: 2017,
        featured: false,
        status: 'active',
        ceo: 'Assaf Resnick',
        website: 'https://www.bigpanda.io/',
        favicon: 'assets/Favicons/bigpanda favicon.png',
        bg: 'assets/portfolio bgs/Bigpanda bg.png',
        logo: 'assets/portfolio logo colors/bigpanda logo color.svg',
    },
    {
        id: 'capitolis',
        name: 'Capitolis',
        sector: 'Fintech',
        category: 'fintech',
        description: 'Safer and more Vibrant Capital Markets',
        round: 'Series D',
        year: 2022,
        featured: false,
        status: 'active',
        ceo: 'Gil Mandelzis',
        website: 'https://capitolis.com/',
        favicon: 'assets/Favicons/Capitolis favicon.png',
        bg: 'assets/portfolio bgs/Capitolis bg.png',
        logo: 'assets/portfolio logo colors/Capitolis logo color.webp',
    },
    {
        id: 'goodship',
        name: 'GoodShip',
        sector: 'Vertical AI',
        category: 'vertical-ai',
        description: 'AI Freight Orchestration & Procurement',
        round: 'Led Series B',
        year: 2025,
        featured: false,
        status: 'active',
        ceo: 'Ryan Soskin',
        website: 'https://www.goodship.io/',
        favicon: 'assets/Favicons/Goodship favicon.png',
        bg: 'assets/portfolio bgs/Goodship bg.png',
        logo: 'assets/portfolio logo colors/goodship logo color.png',
    },
    {
        id: 'regulus',
        name: 'Regulus',
        sector: 'Defense',
        category: 'defense',
        description: 'Next Generation Counter Unmanned Systems',
        round: 'Led Series C',
        year: 2025,
        featured: false,
        status: 'active',
        ceo: 'Yonatan Zur',
        website: 'https://regulus.com/',
        favicon: 'assets/Favicons/regulus favicon.png',
        bg: 'assets/portfolio bgs/regulus bg.png',
        logo: 'assets/portfolio logo colors/regulus color.png',
    },
    {
        id: 'commcrete',
        name: 'Commcrete',
        sector: 'Defense',
        category: 'defense',
        description: 'Connect Beyond Borders',
        round: 'Led Series A',
        year: 2025,
        featured: false,
        status: 'active',
        ceo: 'Itzik Daniel Michaeli',
        website: 'https://www.commcrete.com/',
        favicon: 'assets/Favicons/Commcrete.png',
        bg: 'assets/portfolio bgs/Commcrete.png',
        logo: 'assets/portfolio logo colors/Commcrete logo color.png',
    },

    // ── New portfolio additions ──────────────────────────────────────────

    {
        id: 'avanan',
        name: 'Avanan',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'Reinventing Email Security',
        round: 'Led Series A',
        year: 2016,
        featured: false,
        status: 'exited',
        ceo: 'Gil Friedrich',
        website: 'http://avanan.com/',
        favicon: 'assets/Favicons/Avanan favicon.png',
        bg: 'assets/portfolio bgs/Avanan bg.png',
        logo: 'assets/portfolio logo colors/Avanan logo color.png',
    },
    {
        id: 'cynet',
        name: 'Cynet',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'All-in-One Cybersecurity Platform',
        round: 'Led Series C',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Jason Magee',
        website: 'http://cynet.com/',
        favicon: 'assets/Favicons/cynet favicon.png',
        bg: 'assets/portfolio bgs/Cynet bg.png',
        logo: 'assets/portfolio logo colors/Cynet logo color.svg',
    },
    {
        id: 'dustphotonics',
        name: 'DustPhotonics',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'Optical Communication with Silicon Photonics',
        round: 'Led Series B',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Ronnen Lovinger',
        website: 'http://dustphotonics.com/',
        favicon: 'assets/Favicons/dustphotonics favicon.png',
        bg: 'assets/portfolio bgs/dustphotonics bg.png',
        logo: 'assets/portfolio logo colors/dustphotonics logo color.svg',
    },
    {
        id: 'eleos',
        name: 'Eleos',
        sector: 'Vertical AI',
        category: 'vertical-ai',
        description: 'Automation and AI Solutions for Healthcare',
        round: 'Led Series C',
        year: 2024,
        featured: false,
        status: 'active',
        ceo: 'Alon Joffe',
        website: 'https://eleos.health/',
        favicon: 'assets/Favicons/eleos favicon.png',
        bg: 'assets/portfolio bgs/eleos bg.png',
        logo: 'assets/portfolio logo colors/Eleos logo color.png',
    },
    {
        id: 'equitybee',
        name: 'EquityBee',
        sector: 'Fintech',
        category: 'fintech',
        description: 'Startup Equity Unlocked',
        round: 'Series B',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Oren Barzilai',
        website: 'https://equitybee.com/',
        favicon: 'assets/Favicons/equitybee favicon.png',
        bg: 'assets/portfolio bgs/equitybee bg.png',
        logo: 'assets/portfolio logo colors/Equitybee logo color.svg',
    },
    {
        id: 'flolive',
        name: 'floLIVE',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'The First Global Hyperlocal Network',
        round: 'Led Series C',
        year: 2023,
        featured: false,
        status: 'active',
        ceo: 'Nir Shalom',
        website: 'https://flolive.net/',
        favicon: 'assets/Favicons/flolive favicon.png',
        bg: 'assets/portfolio bgs/flolive bg.png',
        logo: 'assets/portfolio logo colors/floLIVE logo color.svg',
    },
    {
        id: 'guardicore',
        name: 'Guardicore',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'Stopping Ransomware so you\'re Unstoppable',
        round: 'Led Series B',
        year: 2017,
        featured: false,
        status: 'exited',
        ceo: 'Pavel Gurvich',
        website: 'http://www.guardicore.com/',
        favicon: 'assets/Favicons/Guardicore favicon.png',
        bg: 'assets/portfolio bgs/Guardicore bg.png',
        logo: 'assets/portfolio logo colors/guardicore logo color.svg',
    },
    {
        id: 'mixtiles',
        name: 'Mixtiles',
        sector: 'Internet / Digital Media',
        category: 'internet',
        description: 'Create the Home you Love',
        round: 'Led Series B',
        year: 2019,
        featured: false,
        status: 'active',
        ceo: 'Shay Eyal',
        website: 'http://mixtiles.com/',
        favicon: 'assets/Favicons/mixtiles favicon.png',
        bg: 'assets/portfolio bgs/Mixtiles bg.png',
        logo: 'assets/portfolio logo colors/mixtiles logo color.avif',
    },
    {
        id: 'oligo',
        name: 'Oligo Security',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'AppSec Like You\'ve Never Seen Before',
        round: 'Led Series B',
        year: 2024,
        featured: false,
        status: 'active',
        ceo: 'Nadav Czerninski',
        website: 'https://www.oligo.security/',
        favicon: 'assets/Favicons/Oligo Favicon.png',
        bg: 'assets/portfolio bgs/Oligo bg.png',
        logo: 'assets/portfolio logo colors/Oligo security new logo black.png',
    },
    {
        id: 'panorays',
        name: 'Panorays',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'Third-Party Cybersecurity, Shaped for Your Risk DNA',
        round: 'Led Series B',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Matan Or-El',
        website: 'http://panorays.com/',
        favicon: 'assets/Favicons/Panorays favicon.png',
        bg: 'assets/portfolio bgs/Panorays bg.png',
        logo: 'assets/portfolio logo colors/Panorays logo color.svg',
    },
    {
        id: 'planck',
        name: 'Planck',
        sector: 'Fintech',
        category: 'fintech',
        description: 'AI Data Platform for Commercial Insurance',
        round: 'Series B',
        year: 2021,
        featured: false,
        status: 'exited',
        ceo: 'Elad Tsur',
        website: 'https://planckdata.com/',
        favicon: 'assets/Favicons/Planck favicon.png',
        bg: 'assets/portfolio bgs/Planck bg.png',
        logo: 'assets/portfolio logo colors/Planck logo color.avif',
    },
    {
        id: 'quali',
        name: 'Quali',
        sector: 'IT Infrastructure',
        category: 'it-infra',
        description: 'Cloud Infrastructure, Fast and Efficient',
        round: 'Led Series C',
        year: 2020,
        featured: false,
        status: 'active',
        ceo: 'Lior Koriat',
        website: 'http://quali.com/',
        favicon: 'assets/Favicons/Quali favicon.png',
        bg: 'assets/portfolio bgs/Quali bg.png',
        logo: 'assets/portfolio logo colors/Quali logo color.avif',
    },
    {
        id: 'sett',
        name: 'Sett',
        sector: 'Vertical AI',
        category: 'vertical-ai',
        description: 'Creative Performance AI Platform',
        round: 'Led Series B',
        year: 2026,
        featured: false,
        status: 'active',
        ceo: 'Amit Carmi',
        website: 'https://www.sett.ai/',
        favicon: 'assets/Favicons/Sett favicon.png',
        bg: 'assets/portfolio bgs/Sett bg.png',
        logo: 'assets/portfolio logo colors/sett-logo.svg',
    },

];
