/**
 * Greenfield Partners — Portfolio Company Data
 * Single source of truth for all portfolio companies.
 * Assets live in:
 *   Favicons    → assets/Favicons/<name>
 *   BG images   → assets/portfolio bgs/<name>
 *   Color logos  → assets/portfolio logo colors/<name>
 *   White logos  → assets/portfolio assets/portfolio logos w/<name>
 */

const PORTFOLIO = [

    // ── Currently on Dashboard ─────────────────────────────────────────────

    {
        id: 'vast',
        name: 'VAST Data',
        sector: 'AI Infrastructure',
        category: 'ai-infra',
        description: 'The Data Platform Company for the AI Era',
        longDescription: 'VAST Data is the industry\'s only provider of AI infrastructure architected from the ground up to power deep learning and GPU-accelerated data centers and clouds.',
        round: 'Led Series B',
        year: 2019,
        featured: true,
        status: 'active',
        ceo: 'Renen Hallak',
        dealTeam: ['Avery Schwartz (Board Observer)', 'Yuda Doron', 'Shay Grinfeld', 'Raz Mangel'],
        testimonial: {
            quote: 'When we first partnered with Greenfield, they rolled up their sleeves, dug into the Excel, and helped us highlight how the company could shine through the metrics. Greenfield brought an analytical perspective that we didn\'t have internally, guiding us throughout our entire journey. They were true professionals in every interaction, and from the initial investment onward, they consistently acted in the best interests of the company at every step.',
            author: 'Renen Hallak',
        },
        website: 'http://vastdata.com/',
        favicon: 'assets/Favicons/vast favicon.png',
        bg: 'assets/portfolio bgs/vast bg.png',
        logo: 'assets/portfolio logo colors/VAST Data logo color.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/VAST w.svg',
    },
    {
        id: 'coralogix',
        name: 'Coralogix',
        sector: 'IT Infrastructure',
        category: 'it-infra',
        description: 'Observability and Security that Scale with You',
        longDescription: 'Coralogix is the leading stateful streaming platform for modern engineering teams, rebuilding the path to observability using a real-time streaming analytics pipeline that provides monitoring, visualization, and alerting capabilities without the burden of indexing. Its mission is to make observability accessible to all, enabling users to define different data pipelines per use case, providing deep insights for less than half the cost.',
        round: 'Led Series C',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Ariel Assaraf',
        dealTeam: ['Shay Grinfeld (Board Member)', 'Raz Mangel', 'Meir Cohen'],
        testimonial: {
            quote: 'Greenfield partnered with us at a critical point in our company\'s growth. They introduced us to key metrics for our north star, helping us focus on what truly drives growth. With their guidance we became a data-driven company, providing us with the expertise we needed to scale effectively.',
            author: 'Ariel Assaraf',
        },
        website: 'https://www.coralogix.com/',
        favicon: 'assets/Coralogix/cropped-cropped-favicon-192x192.png',
        bg: 'assets/portfolio bgs/coralogix bg.png',
        logo: 'assets/portfolio logo colors/Coralogix Logo Use.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/coralogix w.svg',
    },
    {
        id: 'exodigo',
        name: 'Exodigo',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'Non-Intrusive Subsurface Imaging',
        longDescription: 'Exodigo is the leading underground mapping solution for non-intrusive discovery. Their platforms combine multi-sensor fusion, 3D imaging, and AI technologies to create complete, accurate underground maps that enable confident decision-making for customers across the built world. Exodigo transforms the project lifecycle for customers, who include key community stakeholders in the utilities, transportation and government sectors.',
        round: 'Led Series A',
        year: 2023,
        featured: false,
        status: 'active',
        ceo: 'Jeremy Suard',
        dealTeam: ['Raz Mangel (Board Member)', 'Ortal Sasson', 'Lior Sulkin-Levy'],
        testimonial: {
            quote: 'We wanted a conversation with investors who truly understand us. I value investors who recognize that I need the freedom to make my own mistakes and ultimately make my own decisions. The Greenfield team grasped this quickly, which is exactly what I was looking for. We\'re a complex business, but that instant click of understanding, which we saw during the due diligence process, was exactly what we needed.',
            author: 'Jeremy Suard',
        },
        website: 'http://exodigo.com/',
        favicon: 'assets/Favicons/exodigo favicon.png',
        bg: 'assets/portfolio bgs/exodigo bg.png',
        logo: 'assets/portfolio logo colors/Exodigo logo color.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/exodigo w.svg',
    },
    {
        id: 'robco',
        name: 'RobCo',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'The Robot Company centered on Software and AI',
        longDescription: 'RobCo develops AI-driven robotic systems that bring learning and autonomy into industrial operations. Its Autonomous Manufacturing Platform combines modular industrial hardware with a Physical AI software stack that enables fast deployment, continuous improvement, and application-specific performance. Delivered through a recurring robotics-as-a-service model, RobCo helps industrial companies automate manual tasks while minimizing operational complexity and risk.',
        round: 'Series C',
        year: 2026,
        featured: false,
        status: 'active',
        ceo: 'Roman Hölzl',
        dealTeam: ['Raz Mangel', 'Josh Trup'],
        testimonial: null,
        website: 'https://www.rob.co/',
        favicon: 'assets/Favicons/robco favicon.png',
        bg: 'assets/portfolio bgs/robco bg.png',
        logo: 'assets/portfolio logo colors/RobCo logo color.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/RobCo w.png',
    },
    {
        id: 'torq',
        name: 'Torq',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'AI-Native Hyperautomation for Security Teams',
        longDescription: 'Torq Hyperautomation unifies and automates the entire security infrastructure to deliver unparalleled protection and productivity. Torq is leading the way in hyperautomation \u2013 the ability to rapidly identify, vet, integrate, and automate as many business and IT processes as possible. Torq emancipates security teams from manually managing threat detection and remediation at scale, ensuring all of their systems are talking to each other, and working together in concert.',
        round: 'Led Series B',
        year: 2023,
        featured: false,
        status: 'active',
        ceo: 'Ofer Smadari',
        dealTeam: ['Avery Schwartz (Board Member)', 'Itay Inbar', 'Meir Cohen'],
        testimonial: null,
        website: 'https://torq.io/',
        favicon: 'assets/Favicons/torq favicon.png',
        bg: 'assets/portfolio bgs/torq bg.png',
        logo: 'assets/portfolio logo colors/Torq logo color.avif',
        logoWhite: 'assets/portfolio assets/portfolio logos w/Torq w.avif',
    },
    {
        id: 'aai',
        name: 'AAI',
        sector: 'AI Infrastructure',
        category: 'aai',
        description: 'Cracking the Code<br>of Superintelligence',
        longDescription: 'AAI is a team of elite researchers spanning computer science, mathematics, physics, and biology. We are building transformative AI technology that drives new scientific discoveries and reshapes how humanity solves its hardest problems. Our mission is simple: to usher in a new age of discovery by cracking the code of superintelligence.',
        round: 'Series A',
        year: 2025,
        featured: false,
        status: 'active',
        ceo: 'Prof. Amnon Shashua',
        dealTeam: ['Shay Grinfeld', 'Raz Mangel', 'Meir Cohen'],
        testimonial: null,
        website: 'https://doubleai.com/',
        favicon: 'assets/Favicons/AAI favicon.png',
        bg: 'assets/portfolio bgs/aai bg.png',
        logo: 'assets/portfolio logo colors/AAI Logo.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/AAI W.png',
    },
    {
        id: 'silverfort',
        name: 'Silverfort',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'Where Identity Security has Never Gone Before',
        longDescription: 'Silverfort is the leader in Identity Threat Protection, enabling secure authentication and access in a unified manner across all corporate resources, both on-premises and in the cloud, to detect and stop identity-based attacks including account takeover and ransomware propagation. Using patented technology, Silverfort enforces its protection as a layer on top of the customer\u2019s existing IAM infrastructure, without requiring modifications to endpoints, servers or applications \u2013 capabilities unmatched in the market.',
        round: 'Led Series C',
        year: 2022,
        featured: false,
        status: 'active',
        ceo: 'Hed Kovetz',
        dealTeam: ['Avery Schwartz (Board Member)', 'Raz Mangel', 'Ortal Sasson'],
        testimonial: null,
        website: 'http://silverfort.com/',
        favicon: 'assets/Favicons/silverfort favicon.png',
        bg: 'assets/portfolio bgs/silverfort bg.png',
        logo: 'assets/portfolio logo colors/Silverfort Logo Use.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/Silverfort w.png',
    },

    // ── Staged — ready to pull into dashboard ─────────────────────────────

    {
        id: 'bigpanda',
        name: 'BigPanda',
        sector: 'IT Infrastructure',
        category: 'it-infra',
        description: 'Event Correlation & Automation Platform',
        longDescription: 'BigPanda helps businesses prevent and resolve IT outages with its platform for Event Correlation and Automation, powered by AIOps. BigPanda captures alerts, changes, and topology data from across an enterprise\u2019s disparate tools and uses machine learning to reduce IT noise, detect incidents, and surface their probable root cause \u2013 in real time.',
        round: 'Led Series B',
        year: 2017,
        featured: false,
        status: 'active',
        ceo: 'Assaf Resnick',
        dealTeam: ['Shay Grinfeld (Board Member)', 'Yuda Doron', 'Raz Mangel'],
        testimonial: {
            quote: 'Greenfield invested the time to build a trusting relationship with us over the years. My experience with Shay and the team convinced me that having smart, pleasant partners is more valuable than just big investor names\u2014they help you make good decisions in both good times and bad. As a young company, we hadn\u2019t fully considered scaling, organizational DNA, or data-driven strategies, but Greenfield\u2019s involvement opened our eyes and made us much smarter about building a scalable, data-driven company.',
            author: 'Assaf Resnick',
        },
        website: 'https://www.bigpanda.io/',
        favicon: 'assets/Favicons/bigpanda favicon.png',
        bg: 'assets/portfolio bgs/Bigpanda bg.png',
        logo: 'assets/portfolio logo colors/bigpanda logo color.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/bigpanda w.svg',
    },
    {
        id: 'capitolis',
        name: 'Capitolis',
        sector: 'Fintech',
        category: 'fintech',
        description: 'Safer and more Vibrant Capital Markets',
        longDescription: 'Capitolis is the leading capital marketplace that drives financial resource optimization for market participants, reimagining how capital markets operate. Founded in 2017, Capitolis\u2019 technology enables financial institutions to optimize their resources, execute seamlessly with new market participants, and achieve greater access to more diversified capital, all of which enable fairer, safer, and healthier capital markets.',
        round: 'Series D',
        year: 2022,
        featured: false,
        status: 'active',
        ceo: 'Gil Mandelzis',
        dealTeam: ['Shay Grinfeld (Board Observer)', 'Avery Schwartz', 'Ortal Sasson'],
        testimonial: null,
        website: 'https://capitolis.com/',
        favicon: 'assets/Favicons/Capitolis favicon.png',
        bg: 'assets/portfolio bgs/Capitolis bg.png',
        logo: 'assets/portfolio logo colors/Capitolis logo color.webp',
        logoWhite: 'assets/portfolio assets/portfolio logos w/capitolis w.avif',
    },
    {
        id: 'goodship',
        name: 'GoodShip',
        sector: 'Vertical AI',
        category: 'vertical-ai',
        description: 'AI Freight Orchestration & Procurement',
        longDescription: 'GoodShip is the pioneer in freight orchestration and procurement. Purpose-built for enterprise shippers, the platform unifies fragmented supply chain data, surfaces real-time insights, and helps teams move from reactive firefighting to proactive, coordinated decision-making across truckload, LTL, and spot markets.',
        round: 'Led Series B',
        year: 2025,
        featured: false,
        status: 'active',
        ceo: 'Ryan Soskin',
        dealTeam: ['Itay Inbar (Board Member)', 'Shay Grinfeld (Board Observer)', 'Olivia Levine'],
        testimonial: null,
        website: 'https://www.goodship.io/',
        favicon: 'assets/Favicons/Goodship favicon.png',
        bg: 'assets/portfolio bgs/Goodship bg.png',
        logo: 'assets/portfolio logo colors/goodship logo color.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/goodship w.png',
    },
    {
        id: 'regulus',
        name: 'Regulus',
        sector: 'Defense',
        category: 'defense',
        description: 'Next Generation Counter Unmanned Systems',
        longDescription: 'Regulus Cyber is a leading expert in software-based GPS/GNSS security with two product lines \u2013 Ring C-UxS \u2013 providing groundbreaking C-UxS capabilities against uncrewed systems, and Pyramid GNSS \u2013 protecting against GNSS spoofing & jamming attacks. Both technologies are commercial and employed by Defense, Police and HLS, and defense units worldwide.',
        round: 'Led Series B',
        year: 2025,
        featured: false,
        status: 'active',
        ceo: 'Yonatan Zur',
        dealTeam: ['Raz Mangel (Board Member)', 'Meir Cohen', 'Josh Trup'],
        testimonial: null,
        website: 'https://regulus.com/',
        favicon: 'assets/Favicons/regulus favicon.png',
        bg: 'assets/portfolio bgs/regulus bg.png',
        logo: 'assets/portfolio logo colors/regulus color.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/Regulus w.png',
    },
    {
        id: 'commcrete',
        name: 'Commcrete',
        sector: 'Defense',
        category: 'defense',
        description: 'Connect Beyond Borders',
        longDescription: 'Commcrete is a deep-tech SATCOM solutions company delivering breakthrough satellite communication systems for emergency, remote commercial operations and defense. With a platform engineered for low-profile, high-reliability, rapid-deployment in austere environments, Commcrete offers plug-and-play solutions that combine critical C4I capabilities with energy efficiency, stealth, and unmatched simplicity.',
        round: 'Led Series A',
        year: 2025,
        featured: false,
        status: 'active',
        ceo: 'Itzik Daniel Michaeli',
        dealTeam: ['Raz Mangel (Board Member)', 'Meir Cohen'],
        testimonial: null,
        website: 'https://www.commcrete.com/',
        favicon: 'assets/Favicons/Commcrete.png',
        bg: 'assets/portfolio bgs/Commcrete.png',
        logo: 'assets/portfolio logo colors/Commcrete logo color.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/commcrete w.png',
    },

    // ── New portfolio additions ──────────────────────────────────────────

    {
        id: 'avanan',
        name: 'Avanan',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'Reinventing Email Security',
        longDescription: 'Avanan is a cloud email security platform that pioneered a new approach to prevent sophisticated attacks. Avanan uses APIs to scan for phishing, malware, and data leakage in the line of communications traffic, enabling it to catch threats missed by Microsoft, while adding a transparent layer of security for the entire suite and other collaboration tools like Slack.',
        round: 'Led Series A',
        year: 2016,
        featured: false,
        status: 'exited',
        exitLabel: 'Acquired by Check Point',
        ceo: 'Gil Friedrich',
        dealTeam: ['Yuda Doron', 'Raz Mangel'],
        testimonial: null,
        website: 'http://avanan.com/',
        favicon: 'assets/Favicons/Avanan favicon.png',
        bg: 'assets/portfolio bgs/Avanan bg.png',
        logo: 'assets/portfolio logo colors/Avanan logo color.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/avanan w.svg',
    },
    {
        id: 'cynet',
        name: 'Cynet',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'All-in-One Cybersecurity Platform',
        longDescription: 'Cynet 360 is the world\'s first Autonomous Breach Protection platform that natively integrates XDR endpoint, user and network attack prevention and detection capabilities with an incident engine that fully automates investigation and remediation actions, backed by a 24/7 world-class MDR service. End to end, fully automated breach protection is now within reach of any organization, regardless of security team size and skill level.',
        round: 'Led Series C',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Jason Magee',
        dealTeam: ['Avery Schwartz (Board Member)', 'Daniel Milstein', 'Ortal Sasson'],
        testimonial: null,
        website: 'http://cynet.com/',
        favicon: 'assets/Favicons/cynet favicon.png',
        bg: 'assets/portfolio bgs/Cynet bg.png',
        logo: 'assets/portfolio logo colors/Cynet logo color.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/cynet w.svg',
    },
    {
        id: 'dustphotonics',
        name: 'DustPhotonics',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'Optical Communication with Silicon Photonics',
        longDescription: 'DustPhotonics designs and manufactures high-speed optical communication solutions for data centers, high performance computing and enterprise networks, offering a new standard to optimize high volume data center connectivity, performance and reliability, and best in class alignment.',
        round: 'Led Series B',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Ronnen Lovinger',
        dealTeam: ['Yuda Doron (Board Member)', 'Itay Inbar'],
        testimonial: null,
        website: 'http://dustphotonics.com/',
        favicon: 'assets/Favicons/dustphotonics favicon.png',
        bg: 'assets/portfolio bgs/dustphotonics bg.png',
        logo: 'assets/portfolio logo colors/dustphotonics logo color.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/dustphotonics w.svg',
    },
    {
        id: 'eleos',
        name: 'Eleos',
        sector: 'Vertical AI',
        category: 'vertical-ai',
        description: 'Automation and AI Solutions for Healthcare',
        longDescription: 'Eleos is transforming behavioral healthcare by empowering providers with innovative, AI-driven technology tailored to their unique needs. Our platform redefines clinical workflows by streamlining documentation, simplifying compliance, and uncovering actionable insights to enhance care outcomes. Leveraging the industry\u2019s most extensive dataset of real-world behavioral health sessions, Eleos combines advanced AI capabilities with clinical expertise to deliver tools that significantly reduce administrative burdens, allowing providers to dedicate more time to what truly matters\u2014caring for their clients.',
        round: 'Led Series C',
        year: 2024,
        featured: false,
        status: 'active',
        ceo: 'Alon Joffe',
        dealTeam: ['Shay Grinfeld (Board Member)', 'Itay Inbar'],
        testimonial: null,
        website: 'https://eleos.health/',
        favicon: 'assets/Favicons/eleos favicon.png',
        bg: 'assets/portfolio bgs/eleos bg.png',
        logo: 'assets/portfolio logo colors/Eleos logo color.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/eleos w.png',
    },
    {
        id: 'equitybee',
        name: 'EquityBee',
        sector: 'Fintech',
        category: 'fintech',
        description: 'Startup Equity Unlocked',
        longDescription: 'EquityBee is an employee-focused stock options funding solution that empowers startup employees to exercise their stock options and participate in the success of the company they helped build. EquityBee\u2019s Investor Network provides the capital that startup builders need to exercise their stock options and become shareholders.',
        round: 'Series B',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Oren Barzilai',
        dealTeam: ['Avery Schwartz (Board Observer)'],
        testimonial: null,
        website: 'https://equitybee.com/',
        favicon: 'assets/Favicons/equitybee favicon.png',
        bg: 'assets/portfolio bgs/equitybee bg.png',
        logo: 'assets/portfolio logo colors/Equitybee logo color.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/equitybee w.svg',
    },
    {
        id: 'flolive',
        name: 'floLIVE',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'The First Global Hyperlocal Network',
        longDescription: 'floLIVE offers the largest hyperlocal, global data network, providing centrally managed local connectivity for any device, anywhere. With floLIVE, customers gain direct network access, control connectivity, monitor devices, access real-time events, switch operators remotely, and troubleshoot ahead of time for seamless device performance.',
        round: 'Led Series C',
        year: 2023,
        featured: false,
        status: 'active',
        ceo: 'Nir Shalom',
        dealTeam: ['Avery Schwartz (Board Member)', 'Meir Cohen'],
        testimonial: null,
        website: 'https://flolive.net/',
        favicon: 'assets/Favicons/flolive favicon.png',
        bg: 'assets/portfolio bgs/flolive bg.png',
        logo: 'assets/portfolio logo colors/floLIVE logo color.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/flolive w.svg',
    },
    {
        id: 'guardicore',
        name: 'Guardicore',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'Stopping Ransomware so you\'re Unstoppable',
        longDescription: 'Guardicore offers a hybrid cloud security solution that protects an enterprise\u2019s core assets using flexible, rapidly deployed, and easy to understand micro-segmentation controls. Guardicore\u2019s coercive control layer provides a simpler, faster way to guarantee persistent and consistent security \u2013 for any application, and any IT environment.',
        round: 'Led Series B',
        year: 2017,
        featured: false,
        status: 'exited',
        exitLabel: 'Acquired by Akamai',
        ceo: 'Pavel Gurvich',
        dealTeam: ['Yuda Doron', 'Avery Schwartz', 'Raz Mangel'],
        testimonial: null,
        website: 'http://www.guardicore.com/',
        favicon: 'assets/Favicons/Guardicore favicon.png',
        bg: 'assets/portfolio bgs/Guardicore bg.png',
        logo: 'assets/portfolio logo colors/guardicore logo color.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/guardicore w.svg',
    },
    {
        id: 'mixtiles',
        name: 'Mixtiles',
        sector: 'Internet / Digital Media',
        category: 'internet',
        description: 'Create the Home you Love',
        longDescription: null,
        round: 'Led Series B',
        year: 2019,
        featured: false,
        status: 'active',
        ceo: 'Shay Eyal',
        dealTeam: ['Shay Grinfeld (Board Member)', 'Raz Mangel'],
        testimonial: null,
        website: 'http://mixtiles.com/',
        favicon: 'assets/Favicons/mixtiles favicon.png',
        bg: 'assets/portfolio bgs/Mixtiles bg.png',
        logo: 'assets/portfolio logo colors/mixtiles logo color.avif',
        logoWhite: 'assets/portfolio assets/portfolio logos w/mixtiles w.avif',
    },
    {
        id: 'oligo',
        name: 'Oligo Security',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'AppSec Like You\'ve Never Seen Before',
        longDescription: 'Oligo protects applications against attackers with the industry\u2019s leading Application Detection and Response (ADR) platform. With deep application inspection through real-time monitoring and context-aware analysis, Oligo enables customers to instantly see all of the vulnerabilities in their environments, identify those that matter most, and stop application-based attacks in their tracks.',
        round: 'Led Series B',
        year: 2024,
        featured: false,
        status: 'active',
        ceo: 'Nadav Czerninski',
        dealTeam: ['Avery Schwartz (Board Member)', 'Raz Mangel', 'Josh Trup'],
        testimonial: null,
        website: 'https://www.oligo.security/',
        favicon: 'assets/Favicons/Oligo Favicon.png',
        bg: 'assets/portfolio bgs/Oligo bg.png',
        logo: 'assets/portfolio logo colors/Oligo security new logo black.png',
        logoWhite: 'assets/portfolio assets/portfolio logos w/Oligo security logo white.png',
    },
    {
        id: 'panorays',
        name: 'Panorays',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'Third-Party Cybersecurity, Shaped for Your Risk DNA',
        longDescription: 'Panorays is a provider of third-party security risk management software, offered as a SaaS-based platform. The company serves enterprise and mid-market customers primarily in North America, the UK and the EU, and has been adopted by leading banking, insurance, financial services and healthcare organizations, among others.',
        round: 'Led Series B',
        year: 2021,
        featured: false,
        status: 'active',
        ceo: 'Matan Or-El',
        dealTeam: ['Avery Schwartz (Board Member)', 'Itay Inbar'],
        testimonial: null,
        website: 'http://panorays.com/',
        favicon: 'assets/Favicons/Panorays favicon.png',
        bg: 'assets/portfolio bgs/Panorays bg.png',
        logo: 'assets/portfolio logo colors/Panorays logo color.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/Panorays w.svg',
    },
    {
        id: 'planck',
        name: 'Planck',
        sector: 'Fintech',
        category: 'fintech',
        description: 'AI Data Platform for Commercial Insurance',
        longDescription: 'Planck provides an AI-based data platform for commercial insurance and works with top US insurance companies to help them increase premiums while reducing loss and expense ratios. Its mission is to empower commercial insurers by generating insights that streamline the commercial underwriting process, enabling insurers to instantly and accurately underwrite any policy.',
        round: 'Series B',
        year: 2021,
        featured: false,
        status: 'exited',
        exitLabel: 'Acquired by Applied Systems',
        ceo: 'Elad Tsur',
        dealTeam: ['Yuda Doron (Board Observer)', 'Raz Mangel', 'Meir Cohen'],
        testimonial: null,
        website: 'https://planckdata.com/',
        favicon: 'assets/Favicons/Planck favicon.png',
        bg: 'assets/portfolio bgs/Planck bg.png',
        logo: 'assets/portfolio logo colors/Planck logo color.avif',
        logoWhite: 'assets/portfolio assets/portfolio logos w/Planck w.avif',
    },
    {
        id: 'quali',
        name: 'Quali',
        sector: 'IT Infrastructure',
        category: 'it-infra',
        description: 'Cloud Infrastructure, Fast and Efficient',
        longDescription: 'Quali delivers Infrastructure Automation at Scale to complex on-premise, hybrid, and cloud environments. Quali\u2019s award-winning CloudShell platform creates self-service, on-demand automation solutions that increase engineering productivity, cut cloud costs, and optimize infrastructure utilization.',
        round: 'Led Series C',
        year: 2020,
        featured: false,
        status: 'active',
        ceo: 'Lior Koriat',
        dealTeam: ['Shay Grinfeld (Board Member)', 'Raz Mangel'],
        testimonial: null,
        website: 'http://quali.com/',
        favicon: 'assets/Favicons/Quali favicon.png',
        bg: 'assets/portfolio bgs/Quali bg.png',
        logo: 'assets/portfolio logo colors/Quali logo color.avif',
        logoWhite: 'assets/portfolio assets/portfolio logos w/Quali w.avif',
    },
    {
        id: 'sett',
        name: 'Sett',
        sector: 'Vertical AI',
        category: 'vertical-ai',
        description: 'Creative Performance AI Platform',
        longDescription: 'Building agentic AI that helps mobile game teams find winning creatives faster and grow their games into global hits.',
        round: 'Led Series B',
        year: 2026,
        featured: false,
        status: 'active',
        ceo: 'Amit Carmi',
        dealTeam: ['Raz Mangel (Board Member)', 'Meir Cohen'],
        testimonial: null,
        website: 'https://www.sett.ai/',
        favicon: 'assets/Favicons/Sett favicon.png',
        bg: 'assets/portfolio bgs/Sett bg.png',
        logo: 'assets/portfolio logo colors/sett-logo.svg',
        logoWhite: 'assets/portfolio assets/portfolio logos w/sett w.png',
    },

];
